export { default as Home } from "./Home/Home"
export { default as Products } from "./Products/Products"
export { default as NotFound } from "./NotFound/NotFound"
export { default as SignUp } from "./SignUp/SignUp"
export { default as SignIn } from "./SignIn/SignIn"
export { default as Profile } from "./Profile/Profile"
