export { default as Header } from "./Header/Header"
export { default as DropdownMenu } from "./DropdownMenu/DropdownMenu"
export { default as SearchParameters } from "./SearchParameters/SearchParameters"
export { default as SideMenu } from "./SideMenu/SideMenu"
export { default as DiscountProducts } from "./DiscountProducts/DiscountProducts"
export { default as OurInstagram } from "./OurInstagram/OurInstagram"
